name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Replace with your default branch name if different

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages  # ✅ This line is required now!

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Adjust if your build outputs to a folder like "dist", "build", etc.

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
